apiVersion: v1
kind: Secret
metadata:
  name: acquisitions-secret
  labels:
    app: acquisitions
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neon:password@neon-local:5432/acquisitions"
  API_KEY: "dev-api-key"
  JWT_SECRET: "dev-jwt-secret"
  NEON_API_KEY: "napi_tagqyuq5kt3gcg2l7fkq56i0cd9s24gd9b5iu4775psosvwjav60fpnsa2tnmv0i"
  NEON_PROJECT_ID: "muddy-violet-94047988"
  PARENT_BRANCH_ID: "br-soft-hill-ab2t81f5"


